services:
  tgbot:
    image: ghcr.io/noobmaster-ru/axiomai:main
    container_name: axiomai.tgbot.prod
    env_file:
      - ".env"
    volumes:
      - ./assets:/app/assets
      - ./${SERVICE_ACCOUNT_AXIOMAI}:/app/${SERVICE_ACCOUNT_AXIOMAI}:ro
    restart: unless-stopped
    command: "python -m axiomai.tgbot"

  observer:
    image: ghcr.io/noobmaster-ru/axiomai:main
    container_name: axiomai.observer.prod
    env_file:
      - ".env"
    volumes:
      - ./${SERVICE_ACCOUNT_AXIOMAI}:/app/${SERVICE_ACCOUNT_AXIOMAI}:ro
    restart: unless-stopped
    command: "python -m axiomai.observer"

  api:
    image: ghcr.io/noobmaster-ru/axiomai:main
    container_name: axiomai.api.prod
    env_file:
      - ".env"
    volumes:
      - ./assets:/app/assets
    restart: unless-stopped
    command: "python -m axiomai.api"

  frontend:
    image: ghcr.io/noobmaster-ru/axiomai-frontend:main
    container_name: axiomai.frontend.prod
    env_file:
      - ".env"
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - caddy-data:/data
      - caddy-config:/config

  postgres_migration:
    image: ghcr.io/noobmaster-ru/axiomai:main
    container_name: axiomai.postgres.migration.prod
    env_file:
      - ".env"
    command: "alembic upgrade head"

volumes:
  caddy-config:
  caddy-data:
